board/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from registration.views import *
from board.views import board_list,board_detail,board_write,boardUpdateView,board_delete,comment_delete

urlpatterns = [
    path('list/',board_list,name='list'),
    path('detail/<int:pk>', board_detail,name='detail'),
    path('write/',board_write,name='write'),
    path('update/<int:pk>/',boardUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',board_delete,name='delete'),
    path('delete/comment/<int:pk>',comment_delete,name='comment_delete'),


]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from registration.views import *
from registration.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',IndexView.as_view(),name='index'),
    path('login/', auth_views.LoginView.as_view(),name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(),name = 'logout'),
    path('profile/',profile,name = 'profile'),
    path('register/',register,name='register'),
    path('',include('board.urls')),
    path('summernote/', include('django_summernote.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

class Board(models.Model):
    title = models.CharField(max_length=64,verbose_name='title',default='')
    contents = models.TextField(verbose_name='content',default='')
    # contents = RichTextField(max_length=128, verbose_name='content', default='')
    writer = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="user",default='')
    registered_dttm = models.DateTimeField(auto_now_add=True,verbose_name='시간')





    class Meta:
        db_table = "board"
        verbose_name = "게시글"
        verbose_name_plural="게시글"

        def __str__(self):
            return self.title


class Comment(models.Model):
    board = models.ForeignKey(Board,on_delete=models.CASCADE,related_name='comment')
    author = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='comment_user')
    text = models.TextField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:

        verbose_name = "댓글"
        verbose_name_plural="댓글들"



    def __str__(self):
        return self.text

board/forms.py
from django import forms
from .models import Board
from django.contrib.auth.hashers import check_password
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class WriteForm(forms.Form):
    title = forms.CharField(max_length=64,label="제목",error_messages={'required' : '제목 입력해주세요'})
    contents = forms.CharField(widget=forms.Textarea,label="내용" ,error_messages={'required' : '내용 입력해주세요'})
    class Meta:
        model = Board
        fields=('title','contents',)

class BoardForm(forms.ModelForm):

    title = forms.CharField(max_length=64,label="제목",error_messages={'required' : '제목 입력해주세요'})
    contents = forms.Textarea()
    class Meta:
        model = Board
        fields=('title','contents',)


# class UpdateForm(forms.ModelForm):
#     title = forms.CharField(widget=forms.Textarea,max_length=64,label="제목",error_messages={'required' : '제목 입력해주세요'})
#     contents = forms.CharField(widget=forms.Textarea,label="내용" ,error_messages={'required' : '내용 입력해주세요'})

class FormFromSomeModel(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'special', 'style': 'width:100%;height:37px'}))
    class Meta:
        model = Board
        fields=('title','contents')
        widgets = {
            'contents' : SummernoteWidget()
        }

board/views.py
from django.shortcuts import render,redirect
from .models import Board,Comment
from django.http import Http404,HttpResponse
from django.core.paginator import Paginator
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User
from .forms import BoardForm,WriteForm,FormFromSomeModel
from django.urls import reverse_lazy,reverse
from django.contrib.auth.decorators import login_required

# Create your views here.





def board_detail(request,pk):

    board = Board.objects.get(pk=pk)


    if request.method == 'POST':
        if str(request.user) == "AnonymousUser":
            return redirect('/login')
        Comment.objects.create(
            board = board,
            author = request.user,
            text=request.POST['text']

            )
        # print(board.pk)
        return redirect(f'/detail/{board.pk}')




    return render(request,'board_detail.html',{'board':board})

def comment_delete(request,pk):
    commen = Comment.objects.get(pk=pk)
    if commen.author == request.user:
        commen.delete()
        return redirect(f'/detail/{commen.board.id}')
    else:
        return redirect(f'/detail/{commen.board.id}')

@login_required
def board_write(request):
    # if not request.user.is_authenticated:
    #     return redirect('/login/')

    if request.method == "POST":

        form = WriteForm(request.POST)
        if form.is_valid():
            board = Board()
            board.title = form.cleaned_data['title']
            board.contents = form.cleaned_data['contents']
            board.writer = request.user
            board.save()

            return redirect('/list')
    else:
        form = WriteForm()
    return render(request,'board_write.html',{'form':form})

def board_list(request):

    all_board = Board.objects.all().order_by('-id')
    # comment_count = Comment.objects.filter()



    page = int(request.GET.get('p',1))
    paginator = Paginator(all_board,20)

    boards = paginator.get_page(page)

    q = request.GET.get('q', '')  # GET request의 인자중에 q 값이 있으면 가져오고, 없으면 빈 문자열 넣기
    if q:  # q가 있으면
        boards = all_board.filter(title__icontains=q)



    return render(request,'board_list.html',{'boards':boards,'q':q})


class boardUpdateView(UpdateView):
    model = Board
    form_class = FormFromSomeModel
    template_name = "board_update.html"
    success_url = reverse_lazy('list')

    def get_queryset(self):
        base_qs = super(boardUpdateView, self).get_queryset()
        return base_qs.filter(writer=self.request.user)




def board_delete(request,pk):
    boards = Board.objects.get(pk=pk)
    if boards.writer == request.user:
        boards.delete()
        return redirect('/list')
    else:
        return render(request,'registration/index.html')







# def search(request):
#     q = request.GET.get('q')
#
#     if q:
#         title = BoardDocument.search().query("match",title=q)
#
#     else:
#         boards = ' '
#
#     return render(request,'board_list.html',{'boards':title})

board/templates/base.html
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
    <link rel="stylesheet" href="/static/bootstrap.min (1).css"/>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap" rel="stylesheet">

    <style>
        body{
            font-family: 'Nanum Gothic', sans-serif;
        }
    </style>
    {% block header %}
    {% endblock %}

</head>

<body>
<div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">성명문 모음</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">


          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div >
      <a href="{% url 'index' %}" class="navbar-brand">
        <!--<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>-->
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Baseball_%28crop%29.jpg/1200px-Baseball_%28crop%29.jpg" style="width: 30px">
      </a>
      <a href="{% url 'list' %}" class="navbar-brand">게시판</a>
      <!--{% comment %} <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">-->
        <!--<span class="navbar-toggler-icon"></span>-->
      <!--</button> {% endcomment %}-->


    </div>


    {% if user.is_authenticated %}
      <a href="{% url 'profile' %}"><p style="color: red;float: right;">{{ user.username }}</p></a>
        <a href="{% url 'logout' %}"><button class="btn-danger" style="float: right">로그아웃</button></a>
      {% else %}
      <a href="{% url 'login' %}"><p style="color: red">로그인</p> </a>
      {% endif %}
      <!--<p style="float: right;color: white;font-size: large">{{user.get_username}}s</p>-->


  </div>
</header>


<!--<nav class="navbar navbar-expand-lg navbar-dark bg-primary">-->
  <!--<a class="navbar-brand" href="#">Home</a>-->
  <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
    <!--<span class="navbar-toggler-icon"></span>-->
  <!--</button>-->

  <!--<div class="collapse navbar-collapse" id="navbarSupportedContent">-->
    <!--<ul class="navbar-nav mr-auto">-->
      <!--<li class="nav-item">-->
          <!--{% if user.username == None %}-->
        <!--<a class="nav-link" href="#">Login <span class="sr-only">(current)</span></a>-->
          <!--{% else %}-->
          <!--<a class="nav-link" href="#">Logout <span class="sr-only">(current)</span></a>-->
          <!--{% endif %}-->
      <!--</li>-->
      <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="#">게시판</a>-->
      <!--</li>-->
        <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="#">Link</a>-->
      <!--</li>-->
        <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="#">Link</a>-->
      <!--</li>-->
      <!--<li class="nav-item">-->
        <!--<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">아이디 : {{ user.username }}</a>-->
      <!--</li>-->
    <!--</ul>-->

  <!--</div>-->
<!--</nav>-->
<div class="container">
    {% block contents %}
    {% endblock %}
</div>


</body>

</html>

board/templates/board_confirm_delete.html
{% extends "base.html" %}

{% block contents %}

    <button>삭제하시겠습니까?</button>

{% endblock %}

board/templates/board_detail.html
{% extends "base.html" %}

{% block contents %}
<style>
    /* 이 밑으로는 코멘트와 관련된 스타일입니다. */
    /* 이 안에 둘러쌓인 글은 프로그램에 영향을 미치지 않는 메모입니다. */
    .comment_list {
        background-color: #f0f1f4;
        border-bottom: 1px solid #bcbdc3;
        padding-top: 0.1px;
    }

    .comment {
        background-color: #fff;
        {#border-radius: 30px;#}

        padding: 10px;
        margin-bottom: 10px;
        margin-top: 10px;
        margin-right: 20px;
        margin-left: 20px;
    }

    .comment__date {
        margin: 0 15px;
        padding: 8px 15px;
        padding-bottom: 0px;
        font-size: 13px;
    }

    .name {
        font-weight: bold;
        color: #445994;
    }

    .form-wrapper {

    }

    /* 똑같은 스타일을 적용하고 싶으면 ,를 입력해주면 됩니다. */
    .form-wrapper input,
    .form-wrapper textarea {
        border: 1px solid #ddd;
        width: 95%;
        padding: 5px;
        font-size: 14px;
        box-sizing: border-box;
        border-radius: 5px;
        margin-top: 2px;
        margin-bottom: 5px;
    }

    button {
        border: 1px solid #405ea3;
        background-color: #4967ad;
        color: #fff;
        font-weight: 500;
        font-size: 15px;
        padding: 3px 16px;
        border-radius: 2px;
    }
</style>
<div class="row mt-5">
    <div class="col-12">
        <div class="form-group">
            <!--<label for="title">제목</label>-->
            <!--<input type="text" class="form-control" id="title" placeholder="" name="" value="{{board.title}}" readonly/>-->
            <hr size="10px" color="#2b242f">
            <div>
            <div style="float;"><strong>{{board.title}}</strong></div>
                <div style="float: right; font-size: 12px;">조회 19 | 추천 2 | 댓글 {{ board.comment.count }}</div>


                </div>


            <div>
                <hr>
                <!--<div class="side"><p style="font-size: 12px">개구리잡자</p></div>-->
                <div style="float: left; font-size: 12px;">{{ board.writer }} </div>
                <div style="float: right; font-size: 12px;">{{board.registered_dttm}}</div>

            </div>


            <!--<label for="contetns">내용</label>-->
            <!--<textarea  style="height:300px" class="form-control" readonly>{{board.contents}}</textarea>-->
            <br><br><br>
            {{board.contents | safe}}
        </div>
        <br>

        <div style="margin: auto;width:100px;border: 1px;height: 25px">

            <button class="btn-success btn-sm">따봉  10</button>

        </div>
        <hr>
        <br>

        <a href="{% url 'list' %}"><button class="btn btn-primary">목록</button></a>

        {% if user == board.writer %}
        <a href="{% url 'update' pk=board.id %}"><button class="btn btn-primary">수정</button></a>
            <a href="{% url 'delete' pk=board.id %}"><button class="btn btn-primary">삭제</button></a>
        {% endif %}

    </div>


</div>
<br>
    <div class="form-wrapper">

    <form action="" method="POST">
        {% csrf_token %}
        <div style="">
        <textarea class="comment__date" name="text"  placeholder="댓글"></textarea>
        <button type="submit">등록</button>
            </div>
    </form>
</div>

    <div class="comment_list">
    {% for commen in board.comment.all %}
        {% if commen.author == user %}
                <div class="comment" style=""><span class="name">{{ commen.author }}</span>&nbsp;{{ commen.text }} <div style="float: right">{{ commen.created |date:'m-d h:i' }} <a href="{% url 'comment_delete' pk=commen.id %}">삭제</a></div></div>
        {% else %}
                <div class="comment" style=""><span class="name">{{ commen.author }}</span>&nbsp;{{ commen.text }} <div style="float: right">{{ commen.created |date:'m-d h:i'}}</div></div>


        {% endif %}
    {% endfor %}
</div>
    <br>

{% endblock %}

board/templates/board_list.html
{% extends "base.html" %}

{% block contents %}
<style>
    .search {
  margin: 3em 0 1em 0;
  position: relative; }
  .search-icon {
    position: absolute;
    top: 0.8em;
    left: 1em;
    font-size: 20px;
    color: #C6C6C6; }
  .search-input {
    width: 100%;
    padding: 0.5em 0.8em;
    border-radius: 3px;
    border: 1px solid #ccc;
    padding-left: 2.2em;
    color: #1067BF;
    font-size: 1.5em;
    font-weight: 300; }

</style>
<div class="row mt-5">
    <div class="col-12">
        <form class="search" method="get" action="#">

  <i class="fa fa-search search-icon"></i>
{#  <input class="search-input" id="q" {% if request.GET.q %}value="{{ request.GET.q }}"{% endif %} name="q" type="text" placeholder="your search...">#}
  <input class="search-input" id="q"name="q" type="text" value="{{ q }}" placeholder="검색">

        </form>
        <table class="table table-hover">
            <thead class="text-dark">

            <tr style="font-size: 12px">
                <th>번호</th>
                <th>제목</th>
                <th style="">아이디</th>
                <th>일시</th>
                <th>조회</th>
            </tr>
            </thead>


             <tr style="font-size: 12px">
                <td><strong>공지</strong></td>
                 <td style="color: red;"><strong>[성별관련 언급 공지 제발 좀! 확인]</strong></td>
                <th style="">아이디</th>
                <td>05.13</td>
                <td>12030</td>
            </tr>


            <tbody class="text-dark">
            {% for board in boards %}
            {% now "m-d" as todays_date %}



            <tr style="font-size: 12px">
                <td>{{ board.id }}</td>
                <td><a style="color:#000;" href="{% url 'detail' pk=board.id %}"> {{ board.title }} </a><strong style="color: #005c7a;font-size: smaller"> {{board.comment.count }}</strong></td>
                <!--<td>{{ board.writer }}</td>-->
                <td>{{ board.writer }}</td>
                {% if todays_date == board.registered_dttm|date:'m-d' %}

                <td>{{ board.registered_dttm|date:'H:m' }}</td>
                {% else %}
                <td>{{ board.registered_dttm|date:'m.d' }}</td>
                {% endif %}

                <td>10</td>


            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row mt-2">
    <div class="col-12">
        <nav>
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    {% if boards.has_previous %}
                    <a class="page-link" href="?p={{ boards.previous_page_number}}">이전으로</a>
                    {% else %}
                    <a class="page-link disabled" href="#" disabled="">이전으로</a>
                    {% endif %}
                </li>
                <li class="page-item active">
                    <a class="page-link" href="#">{{ boards.number }}/{{boards.paginator.num_pages}}</a>
                </li>
                <li class="page-item">
                    {% if boards.has_next %}
                    <a class="page-link" href="?p={{ boards.next_page_number }}">다음으로</a>
                    {% else %}
                    <a class="page-link disabled" href="#" >다음으로</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-12" style="text-align: right" >
        <a href="{% url 'write' %}"><button class="btn btn-primary">글쓰기 </button></a>
    </div>
</div>
{% endblock %}

board/templates/board_update.html
{% extends "base.html" %}

{% block header %}
{#    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>#}
    <script src="lang/summernote-ko-KR.js"></script>
{#    <script>#}
{#    $(document).ready(function () {#}
{#        $('#id_contents').summernote({#}
{#        tabsize: 2,#}
{#        height: 400,#}
{#            lang: 'ko-KR'#}
{#      });#}
{##}
{#    })#}
{##}
{#    </script>#}
{% endblock %}
{% block contents %}

{#<div class="row mt-5">#}
{#    <div class="col-12">#}
{#        <form action="." method="post">#}
{#        {% csrf_token %}#}
{#        {% for field in form %}#}
{##}
{#        <div class="form-group">#}
{#            <label for="{{ field.id_for_label }}">{{field.label}}</label>#}
{#            {{ field.field.widget.name }}#}
{#            {% ifequal field.name 'contents' %}#}
{#            <textarea  style="height:300px" class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}" placeholder="{{ field.label }}" >{{ field.value }}</textarea>#}
{#            {% else %}#}
{#            <input type="{{ field.field.widget.input_type }}" value="{{ field.value }}" class="form-control" id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}"/>#}
{#            {% endifequal %}#}
{#        </div>#}
{#        {% if field.errors %}#}
{#        <span style="color: red">{{ field.errors }}</span>#}
{#        {% endif %}#}
{#        {% endfor %}#}
{##}
{#        <button type="submit" class="btn btn-primary">수정</button>#}
{#    </form>#}
{#    </div>#}
{#</div>#}
<div class="row mt-5">
    <div class="col-12">
    <form action="." method="post">
        <div class="form-group">
    {% csrf_token %}

       제목<br><p style="">{{ form.title }}</p>


            내용 <br>
            {{ form.contents }}
            </div>
        <input type="submit" value="수정" class="btn btn-info btn-sm">
    </form>
    </div>
</div>

{% endblock %}

board/templates/board_write.html
{% extends "base.html" %}
{% block header %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>
    <script src="lang/summernote-ko-KR.js"></script>
    <script>
    $(document).ready(function () {
        $('#id_contents').summernote({
        tabsize: 2,
        height: 400,
            lang: 'ko-KR'
      });

    })

    </script>
{% endblock %}
{% block contents %}

<div class="row mt-5">
    <div class="col-12">
        <form action="." method="post">
        {% csrf_token %}
        {% for field in form %}

        <div class="form-group" >
            <label for="{{ field.id_for_label }}">{{field.label}}</label>
            {{ field.field.widget.name }}
            {% ifequal field.name 'contents' %}
            <textarea  style="height:300px" class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}" placeholder="{{ field.label }}"></textarea>
            {% else %}
            <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}"/>
            {% endifequal %}
        </div>
        {% if field.errors %}
        <span style="color: red">{{ field.errors }}</span>
        {% endif %}
        {% endfor %}

        <button type="submit" class="btn btn-primary">글쓰기</button>
    </form>
    </div>
</div>

{#    <form action="." method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button type="submit" class="btn-success">글쓰기</button>#}
{#    </form>#}

{% endblock %}